spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecnutradesystemdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Tudou060405

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的自动转换

datasource:
  master:
    url: jdbc:mysql://localhost:3306/ecnutradesystemdb?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&allowMultiQueries=true
    # 其他配置项...

server:
  port: 8081
